theme: jekyll-theme-minimal
title: CS-499 Capstone Final Project
description: For this project I have selected to elaborate on my CS Eclipse Project "Austin Austin Animal Center." The purpose of the project was to create a data base for the animal shelter.
